# Generated by Django 3.1.3 on 2022-01-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartServices', '0006_auto_20220105_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(default='images/SSDefault.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='slug',
            field=models.SlugField(default='Sido', max_length=255),
        ),
    ]
