# Generated by Django 3.1.3 on 2022-01-08 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SmartServices', '0007_auto_20220108_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='created_by',
            field=models.ForeignKey(default='Sido', on_delete=django.db.models.deletion.CASCADE, related_name='Partner_maker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partners',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
