# Generated by Django 3.1.3 on 2022-01-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartServices', '0009_auto_20220109_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='created_by',
        ),
    ]
