# Generated by Django 3.1.3 on 2022-01-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartServices', '0010_remove_partners_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=255)),
                ('Phone', models.IntegerField()),
                ('Address', models.CharField(max_length=250)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Ammount', models.CharField(max_length=100)),
                ('WokerName', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
    ]
